import type { Guide } from "./guides";

export const rawGuides: Omit<Guide, "slug">[] = [
  // --- Build ---
  {
    kind: "Build",
    title: "Modern Deniz Kenarı Ev",
    category: "Ev",
    description:
      "Sade hatları ve geniş camekanlarıyla sahil kasabalarına yakışan, hızlıca bitirilebilecek modern bir ev tasarımı.",
    gradient: "from-sky-400 to-blue-600",
    difficulty: "Kolay",
    materials: ["Beyaz beton", "Cam", "Meşe kereste", "Gri boyalı terracotta"],
    usesMods: [],
    hasSchematic: false,
    author: "TMPCraft",
    views: 1560,
    setting: "Şehir",
    terrain: ["Kıyı"],
    buildTimeMinutes: 90,
  },
  {
    kind: "Build",
    title: "Ortaçağ Taş Kalesi",
    category: "Kale",
    description:
      "Burçları, iç avlusu ve savunma duvarlarıyla klasik bir ortaçağ kalesi; büyük araziler için tasarlandı.",
    gradient: "from-stone-500 to-neutral-700",
    difficulty: "Zor",
    materials: ["Taş tuğla", "Andezit", "Meşe kazık", "Demir kapı", "Meşale"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 3120,
    setting: "Şehir",
    buildTimeMinutes: 600,
  },
  {
    kind: "Build",
    title: "Büyücü Kulesi",
    category: "Kule",
    description:
      "İçindeki büyü masası ve kitaplık odasıyla mistik bir görünüm sunan, dar ama etkileyici bir kule yapısı.",
    gradient: "from-purple-500 to-indigo-700",
    difficulty: "Orta",
    materials: [
      "Derin dilimli taş",
      "Mor mürekkep camı",
      "Kitaplık",
      "Mürekkep kesesi bloğu",
    ],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 980,
    setting: "Şehir",
    buildTimeMinutes: 240,
  },
  {
    kind: "Build",
    title: "Asma Halat Köprüsü",
    category: "Köprü",
    description:
      "İki uçurum arasını sallanan bir görünümle birleştiren, zincir ve meşe kütüklerden oluşan asma köprü.",
    gradient: "from-amber-600 to-yellow-800",
    difficulty: "Orta",
    materials: ["Zincir", "Meşe kütük", "İp merdiven", "Fener"],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 740,
    setting: "Şehir",
    terrain: ["Dağ"],
    buildTimeMinutes: 150,
  },
  {
    kind: "Build",
    title: "Gizli Piston Kapılı Sığınak",
    category: "Redstone Yapı",
    description:
      "Tek bir düğmeyle açılıp kapanan, dışarıdan fark edilmeyen piston mekanizmalı gizli bir giriş sistemi.",
    gradient: "from-red-500 to-rose-700",
    difficulty: "Zor",
    materials: [
      "Yapışkan piston",
      "Redstone tozu",
      "Tekrarlayıcı",
      "Taş düğmesi",
      "Taş tuğla",
    ],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 2210,
    setting: "Şehir",
    buildTimeMinutes: 90,
  },
  {
    kind: "Build",
    title: "Bulutların Üstünde Yüzen Ada",
    category: "Yüzen Ada",
    description:
      "Zeminden kopmuş gibi görünen, etrafında küçük şelaleler akan dekoratif bir ada yapısı.",
    gradient: "from-cyan-300 to-sky-500",
    difficulty: "Orta",
    materials: ["Çim blok", "Toprak", "Meşe yaprağı", "Taş", "Su kovası"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 1330,
    setting: "Doğal",
    buildTimeMinutes: 300,
  },
  {
    kind: "Build",
    title: "Derinlik Karargahı",
    category: "Yeraltı Üs",
    description:
      "Mağara sistemine gizlenmiş, kendi güç kaynağını ve depolama odalarını barındıran bir yeraltı üssü.",
    gradient: "from-zinc-600 to-slate-800",
    difficulty: "Zor",
    materials: ["Derinlik taşı", "Demir blok", "Cam", "Fener"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 1670,
    setting: "Şehir",
    terrain: ["Mağara"],
    buildTimeMinutes: 420,
  },
  {
    kind: "Build",
    title: "Kıyı Balıkçı Köyü",
    category: "Köy",
    description:
      "İskeleleri, balıkçı kulübeleri ve pazar meydanıyla küçük bir kıyı köyü; köylülerin gerçekten yaşayabileceği bir düzen gözetir.",
    gradient: "from-yellow-600 to-orange-800",
    difficulty: "Zor",
    materials: ["Meşe kereste", "Kum taşı", "Cam", "Saman balyası"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 2040,
    setting: "Şehir",
    terrain: ["Köy", "Kıyı"],
    buildTimeMinutes: 480,
  },
  {
    kind: "Build",
    title: "Creeper Yüzü Piksel Sanatı",
    category: "Piksel Sanat",
    description:
      "Bahçe duvarına ya da ev cephesine kolayca uygulanabilecek, klasik creeper yüzünden oluşan basit bir piksel sanat şablonu.",
    gradient: "from-green-600 to-neutral-900",
    difficulty: "Kolay",
    materials: ["Yeşil yün", "Siyah yün"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 4210,
    setting: "Şehir",
    buildTimeMinutes: 45,
  },
  {
    kind: "Build",
    title: "Sakura Ağaçlı Japon Bahçesi",
    category: "Bahçe",
    description:
      "Çakıl yollar, küçük bir su birikintisi ve sakura ağaçlarıyla huzurlu bir dinlenme köşesi.",
    gradient: "from-pink-400 to-rose-600",
    difficulty: "Kolay",
    materials: ["Çakıl", "Bambu", "Nilüfer yaprağı", "Meşe yaprağı", "Fener"],
    usesMods: [],
    hasSchematic: false,
    author: "modrehberi",
    views: 1890,
    setting: "Doğal",
    terrain: ["Göl"],
    buildTimeMinutes: 120,
  },

  // --- Farm ---
  {
    kind: "Farm",
    title: "Panik Tetiklemeli Demir Çiftliği",
    category: "Demir",
    description:
      "Village & Pillage güncellemesiyle gelen köylü korku mekaniğini kullanan, iki köylüyü kafesteki bir zombiyle korkutup demir golem üreten modern tasarım.",
    gradient: "from-slate-400 to-zinc-600",
    difficulty: "Orta",
    materials: [
      "İş istasyonu bloğu",
      "Yatak",
      "Zombi kafesi",
      "Vagonet ray",
      "Hopper",
    ],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 2870,
    setting: "Şehir",
    terrain: ["Köy"],
    minVersion: "1.14",
    maxVersion: "1.21",
    yieldPerHour: "~500 demir külçesi",
    afkable: true,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Nether Portalı Altın Çiftliği",
    category: "Altın",
    description:
      "Nether portalından sürekli gelen zombileşmiş domuz insanları magma bloklarıyla öldürüp altın külçesine çeviren yüksek verimli bir tasarım.",
    gradient: "from-amber-400 to-yellow-600",
    difficulty: "Orta",
    materials: ["Magma blok", "Nether portalı", "Su kovası", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 1980,
    setting: "Doğal",
    minVersion: "1.16",
    maxVersion: "1.21",
    yieldPerHour: "~800 altın külçesi",
    afkable: true,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Zindan İskelet Deneyim Çiftliği",
    category: "Deneyim",
    description:
      "Zindanlardaki iskelet doğurganını su akıntılarıyla merkezi bir öldürme odasına yönlendiren, düşme hasarıyla çalışan klasik bir deneyim çiftliği.",
    gradient: "from-emerald-400 to-green-600",
    difficulty: "Orta",
    materials: ["Su kovası", "Hopper", "Cam", "Redstone tozu"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 1420,
    setting: "Doğal",
    terrain: ["Mağara"],
    minVersion: "1.9",
    maxVersion: "1.21",
    yieldPerHour: "~30 deneyim seviyesi",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Karanlık Oda Genel Mob Çiftliği",
    category: "Mob",
    description:
      "Yüzeyin üstüne inşa edilen, tamamen karanlık geniş bir doğurma odasından mobları su akıntılarıyla tek bir noktada toplayan genel amaçlı çiftlik.",
    gradient: "from-red-600 to-neutral-800",
    difficulty: "Zor",
    materials: ["Taş", "Su kovası", "Hopper", "Işık geçirmez bloklar"],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 2330,
    setting: "Doğal",
    minVersion: "1.13",
    maxVersion: "1.21",
    yieldPerHour: "~200 ganimet parçası",
    afkable: true,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Piston Hasatlı Otomatik Buğday Tarlası",
    category: "Ekin",
    description:
      "1.11 ile gelen gözlemci bloğunu kullanarak ekinin olgunlaştığı anı algılayıp otomatik hasat yapan piston sistemli tarla.",
    gradient: "from-lime-500 to-green-700",
    difficulty: "Orta",
    materials: ["Su kaynağı", "Yapışkan piston", "Gözlemci", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 1650,
    setting: "Doğal",
    minVersion: "1.11",
    maxVersion: "1.21",
    yieldPerHour: "~300 buğday",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Gözlemcili Şeker Kamışı Çiftliği",
    category: "Şeker Kamışı",
    description:
      "Uzayan şeker kamışını gözlemci bloğuyla tespit edip anında kesen, tamamen otomatik ve kompakt bir tasarım.",
    gradient: "from-green-400 to-lime-600",
    difficulty: "Kolay",
    materials: ["Şeker kamışı", "Yapışkan piston", "Gözlemci", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 1990,
    setting: "Doğal",
    minVersion: "1.11",
    maxVersion: "1.21",
    yieldPerHour: "~400 şeker kamışı",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Deniz Mabedi Guardian Çiftliği",
    category: "Balık",
    description:
      "Update Aquatic ile gelen su mekaniği değişikliklerine göre uyarlanmış, deniz mabedini boşaltıp guardian'ları toplu şekilde avlayan bir kurulum.",
    gradient: "from-blue-400 to-cyan-600",
    difficulty: "Zor",
    materials: ["Süngerimsi taş", "Cam", "Hopper", "Zincir zırh"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 1120,
    setting: "Doğal",
    terrain: ["Kıyı"],
    minVersion: "1.13",
    maxVersion: "1.21",
    yieldPerHour: "~150 çiğ balık ve prizmarin parçası",
    afkable: false,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Nether Tavanı Enderman Çiftliği",
    category: "Ender İnci",
    description:
      "1.18 sonrası mağara üretiminin değişmesiyle yüzeydeki enderman doğumları azalınca topluluğun standart haline gelen nether tavanı tasarımı; endermanları magma bloklarıyla öldürüp inci toplar.",
    gradient: "from-purple-600 to-violet-900",
    difficulty: "Zor",
    materials: ["Obsidyen platform", "Magma blok", "Hopper", "Işık geçirmez bloklar"],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 2650,
    setting: "Doğal",
    minVersion: "1.16",
    maxVersion: "1.21",
    yieldPerHour: "~300 ender inci",
    afkable: true,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Gözlemcili Huş Ağacı Çiftliği",
    category: "Odun",
    description:
      "Fidanın büyümesini gözlemci bloğuyla algılayıp anında kesen, tek katlı huş ağaçlarına uygun kompakt bir odun çiftliği.",
    gradient: "from-yellow-700 to-amber-900",
    difficulty: "Orta",
    materials: ["Huş fidanı", "Kemik unu", "Yapışkan piston", "Gözlemci", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 1240,
    setting: "Doğal",
    terrain: ["Orman"],
    minVersion: "1.11",
    maxVersion: "1.21",
    yieldPerHour: "~250 kütük",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Şampanya Yöntemi Bal Çiftliği",
    category: "Arı/Bal",
    description:
      "Buzzy Bees güncellemesiyle gelen arı mekaniğini kullanan, kamp ateşi dumanıyla arıları sakinleştirip dispenser'la şişe dolduran sokmasız bir tasarım.",
    gradient: "from-yellow-400 to-amber-600",
    difficulty: "Orta",
    materials: ["Arı kovanı", "Kamp ateşi", "Cam şişe", "Dispenser", "Çiçek tarlası"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 1080,
    setting: "Doğal",
    terrain: ["Orman"],
    minVersion: "1.15",
    maxVersion: "1.21",
    yieldPerHour: "~40 bal şişesi",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Sonsuz Taş Jeneratörü",
    category: "Taş Üretici",
    description:
      "Lav ve suyun buluştuğu noktada oluşan taşı gözlemci tetiklemeli pistonla kırıp hopper'a aktaran, kompakt ve sessiz bir jeneratör.",
    gradient: "from-gray-500 to-slate-700",
    difficulty: "Kolay",
    materials: ["Lav kovası", "Su kovası", "Yapışkan piston", "Gözlemci", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 2410,
    setting: "Doğal",
    minVersion: "1.11",
    maxVersion: "1.21",
    yieldPerHour: "~900 taş",
    afkable: true,
    requiresRedstone: true,
  },

  // --- Ek/alternatif Farm tasarımları ---
  {
    kind: "Farm",
    title: "Nüfus Eşiği Demir Çiftliği",
    category: "Demir",
    description:
      "Köylü sayısını golem-başına-köylü eşiğinin üstüne çıkararak korku mekaniğine hiç ihtiyaç duymadan çalışan, daha sessiz ve kurulumu daha basit bir alternatif tasarım.",
    gradient: "from-gray-400 to-slate-600",
    difficulty: "Kolay",
    materials: ["İş istasyonu bloğu", "Yatak", "Çit kapı", "Hopper"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 970,
    setting: "Şehir",
    terrain: ["Köy"],
    minVersion: "1.14",
    maxVersion: "1.21",
    yieldPerHour: "~350 demir külçesi",
    afkable: true,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "End Adaları Enderman Avlanma Alanı",
    category: "Ender İnci",
    description:
      "Nether tavanı tasarımı popülerleşmeden önceki klasik yöntem: End boyutundaki dış adalarda enderman'ların doğal spawn oranı Overworld'e göre çok daha yüksek. Elytra ile ulaşım gerektirir (Java Edition).",
    gradient: "from-slate-700 to-purple-900",
    difficulty: "Zor",
    materials: ["Elytra", "Kılıç", "Su kovası"],
    usesMods: [],
    hasSchematic: false,
    author: "TMPCraft",
    views: 710,
    setting: "Doğal",
    minVersion: "1.9",
    maxVersion: "1.21",
    yieldPerHour: "~15 ender inci",
    afkable: false,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Piston İtmeli Kabak-Karpuz Çiftliği",
    category: "Kabak/Karpuz",
    description:
      "Sapın yanında oluşan meyveyi büyümeyi beklemeden bir pistonla iterek doğrudan item olarak düşüren, redstone tarihinin en eski otomatik çiftlik tasarımlarından biri — gözlemciye bile ihtiyaç duymaz.",
    gradient: "from-orange-500 to-green-700",
    difficulty: "Kolay",
    materials: ["Piston", "Redstone tozu", "Redstone saati", "Toprak", "Kabak/karpuz tohumu"],
    usesMods: [],
    hasSchematic: true,
    author: "modrehberi",
    views: 1250,
    setting: "Doğal",
    minVersion: "1.13",
    maxVersion: "1.21",
    yieldPerHour: "~300 kabak/karpuz",
    afkable: true,
    requiresRedstone: true,
  },
  {
    kind: "Farm",
    title: "Budding Amethyst Geot Hasadı",
    category: "Ametist",
    description:
      "Doğal bir geodun etrafına inşa edilen, zamanla büyüyen ametist kümelerini periyodik olarak toplayan basit bir hasat sistemi. Budding Amethyst bloğunun kendisi Silk Touch dahil hiçbir aletle toplanamaz.",
    gradient: "from-purple-500 to-violet-700",
    difficulty: "Kolay",
    materials: ["Taş kazma"],
    usesMods: [],
    hasSchematic: true,
    author: "TMPCraft",
    views: 640,
    setting: "Doğal",
    terrain: ["Mağara"],
    minVersion: "1.17",
    maxVersion: "1.21",
    yieldPerHour: "~40 ametist parçası",
    afkable: false,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Nether İstihkamı Blaze Çiftliği",
    category: "İksir Malzemesi",
    description:
      "Nether istihkamındaki bir blaze doğurganını çevreleyip mobları düşme hasarıyla ya da yakın dövüşle öldüren, iksir yapımının olmazsa olmazı blaze çubuğunun ana kaynağı. Blaze'ler ateşe bağışıklı olduğundan lav bıçağı işe yaramaz.",
    gradient: "from-orange-600 to-yellow-500",
    difficulty: "Zor",
    materials: ["Taş tuğla", "Merdiven", "Kılıç", "Zırh"],
    usesMods: [],
    hasSchematic: true,
    author: "redstonecu42",
    views: 1580,
    setting: "Doğal",
    minVersion: "1.0",
    maxVersion: "1.21",
    yieldPerHour: "~200 blaze çubuğu",
    afkable: false,
    requiresRedstone: false,
  },
  {
    kind: "Farm",
    title: "Çiftçi Ticareti Zümrüt Döngüsü",
    category: "Zümrüt",
    description:
      "Otomatik bir ekin çiftliğinden gelen buğday, havuç veya patatesi çiftçi köylüsüne satarak sürekli zümrüt üreten, tamamen yenilenebilir bir ticaret sistemi.",
    gradient: "from-emerald-500 to-green-700",
    difficulty: "Orta",
    materials: ["Çiftçi köylüsü", "İş istasyonu", "Hopper"],
    usesMods: [],
    hasSchematic: false,
    author: "TMPCraft",
    views: 890,
    setting: "Şehir",
    terrain: ["Köy"],
    minVersion: "1.14",
    maxVersion: "1.21",
    yieldPerHour: "~120 zümrüt",
    afkable: true,
    requiresRedstone: false,
  },
];
